// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: authorization.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	Outcome_ALLOW               Outcome = 1
	Outcome_DENY                Outcome = 2
	Outcome_UNAVAILABLE         Outcome = 3
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "ALLOW",
		2: "DENY",
		3: "UNAVAILABLE",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"ALLOW":               1,
		"DENY":                2,
		"UNAVAILABLE":         3,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_authorization_proto_enumTypes[0].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_authorization_proto_enumTypes[0]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_PUBLISH            Action = 1
	Action_SUBSCRIBE          Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "PUBLISH",
		2: "SUBSCRIBE",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"PUBLISH":            1,
		"SUBSCRIBE":          2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_authorization_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_authorization_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{1}
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       Outcome                `protobuf:"varint,1,opt,name=outcome,proto3,enum=mqtts.authz.v1.Outcome" json:"outcome,omitempty"`
	ExpiresAtMs   uint64                 `protobuf:"varint,2,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	CacheTtlMs    uint32                 `protobuf:"varint,3,opt,name=cache_ttl_ms,json=cacheTtlMs,proto3" json:"cache_ttl_ms,omitempty"`
	CacheMaxAgeMs uint32                 `protobuf:"varint,4,opt,name=cache_max_age_ms,json=cacheMaxAgeMs,proto3" json:"cache_max_age_ms,omitempty"`
	CacheRevision string                 `protobuf:"bytes,5,opt,name=cache_revision,json=cacheRevision,proto3" json:"cache_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *Decision) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *Decision) GetExpiresAtMs() uint64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *Decision) GetCacheTtlMs() uint32 {
	if x != nil {
		return x.CacheTtlMs
	}
	return 0
}

func (x *Decision) GetCacheMaxAgeMs() uint32 {
	if x != nil {
		return x.CacheMaxAgeMs
	}
	return 0
}

func (x *Decision) GetCacheRevision() string {
	if x != nil {
		return x.CacheRevision
	}
	return ""
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthenticateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Action        Action                 `protobuf:"varint,4,opt,name=action,proto3,enum=mqtts.authz.v1.Action" json:"action,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	HasPayload    bool                   `protobuf:"varint,7,opt,name=has_payload,json=hasPayload,proto3" json:"has_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AuthorizeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthorizeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizeRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *AuthorizeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AuthorizeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthorizeRequest) GetHasPayload() bool {
	if x != nil {
		return x.HasPayload
	}
	return false
}

type BatchAuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AuthorizeRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAuthorizeRequest) Reset() {
	*x = BatchAuthorizeRequest{}
	mi := &file_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAuthorizeRequest) ProtoMessage() {}

func (x *BatchAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*BatchAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *BatchAuthorizeRequest) GetRequests() []*AuthorizeRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type AuthorizationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Decision      *Decision              `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizationResult) Reset() {
	*x = AuthorizationResult{}
	mi := &file_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationResult) ProtoMessage() {}

func (x *AuthorizationResult) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationResult.ProtoReflect.Descriptor instead.
func (*AuthorizationResult) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationResult) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *AuthorizationResult) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

type BatchAuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AuthorizationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAuthorizeResponse) Reset() {
	*x = BatchAuthorizeResponse{}
	mi := &file_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAuthorizeResponse) ProtoMessage() {}

func (x *BatchAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*BatchAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *BatchAuthorizeResponse) GetResults() []*AuthorizationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnownRevision string                 `protobuf:"bytes,1,opt,name=known_revision,json=knownRevision,proto3" json:"known_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionRequest) Reset() {
	*x = RevisionRequest{}
	mi := &file_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionRequest) ProtoMessage() {}

func (x *RevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionRequest.ProtoReflect.Descriptor instead.
func (*RevisionRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *RevisionRequest) GetKnownRevision() string {
	if x != nil {
		return x.KnownRevision
	}
	return ""
}

type RevisionResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Revision string                 `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// A bounded delta from known_revision. Unknown/restarted/too-old histories
	// return is_delta=false and require global invalidation. Old peers therefore
	// retain the original safe global-revision behavior.
	InvalidatedUsernames []string `protobuf:"bytes,2,rep,name=invalidated_usernames,json=invalidatedUsernames,proto3" json:"invalidated_usernames,omitempty"`
	IsDelta              bool     `protobuf:"varint,3,opt,name=is_delta,json=isDelta,proto3" json:"is_delta,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RevisionResponse) Reset() {
	*x = RevisionResponse{}
	mi := &file_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionResponse) ProtoMessage() {}

func (x *RevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionResponse.ProtoReflect.Descriptor instead.
func (*RevisionResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *RevisionResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *RevisionResponse) GetInvalidatedUsernames() []string {
	if x != nil {
		return x.InvalidatedUsernames
	}
	return nil
}

func (x *RevisionResponse) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

// Optional generic JSON bindings chosen by the policy publisher. Every present
// path must match. required_any additionally requires at least one path. A topic
// binding compares to the original MQTT topic instead of equals_string.
type JsonBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	EqualsString  string                 `protobuf:"bytes,2,opt,name=equals_string,json=equalsString,proto3" json:"equals_string,omitempty"`
	EqualsTopic   bool                   `protobuf:"varint,3,opt,name=equals_topic,json=equalsTopic,proto3" json:"equals_topic,omitempty"`
	RequiredAny   bool                   `protobuf:"varint,4,opt,name=required_any,json=requiredAny,proto3" json:"required_any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonBinding) Reset() {
	*x = JsonBinding{}
	mi := &file_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonBinding) ProtoMessage() {}

func (x *JsonBinding) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonBinding.ProtoReflect.Descriptor instead.
func (*JsonBinding) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{8}
}

func (x *JsonBinding) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *JsonBinding) GetEqualsString() string {
	if x != nil {
		return x.EqualsString
	}
	return ""
}

func (x *JsonBinding) GetEqualsTopic() bool {
	if x != nil {
		return x.EqualsTopic
	}
	return false
}

func (x *JsonBinding) GetRequiredAny() bool {
	if x != nil {
		return x.RequiredAny
	}
	return false
}

type PayloadPolicy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Bindings            []*JsonBinding         `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	CaseInsensitiveKeys bool                   `protobuf:"varint,2,opt,name=case_insensitive_keys,json=caseInsensitiveKeys,proto3" json:"case_insensitive_keys,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PayloadPolicy) Reset() {
	*x = PayloadPolicy{}
	mi := &file_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadPolicy) ProtoMessage() {}

func (x *PayloadPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadPolicy.ProtoReflect.Descriptor instead.
func (*PayloadPolicy) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{9}
}

func (x *PayloadPolicy) GetBindings() []*JsonBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *PayloadPolicy) GetCaseInsensitiveKeys() bool {
	if x != nil {
		return x.CaseInsensitiveKeys
	}
	return false
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        Action                 `protobuf:"varint,1,opt,name=action,proto3,enum=mqtts.authz.v1.Action" json:"action,omitempty"`
	TopicFilter   string                 `protobuf:"bytes,2,opt,name=topic_filter,json=topicFilter,proto3" json:"topic_filter,omitempty"`
	PayloadPolicy *PayloadPolicy         `protobuf:"bytes,3,opt,name=payload_policy,json=payloadPolicy,proto3" json:"payload_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_authorization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{10}
}

func (x *Permission) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Permission) GetTopicFilter() string {
	if x != nil {
		return x.TopicFilter
	}
	return ""
}

func (x *Permission) GetPayloadPolicy() *PayloadPolicy {
	if x != nil {
		return x.PayloadPolicy
	}
	return nil
}

type Session struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PasswordSha256 []byte                 `protobuf:"bytes,3,opt,name=password_sha256,json=passwordSha256,proto3" json:"password_sha256,omitempty"`
	ExpiresAtMs    uint64                 `protobuf:"varint,4,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	// Projection lease: at most five minutes ahead. A publisher outage cannot
	// keep renewing policy grants. Renewing this never extends session expiry.
	PolicyValidUntilMs uint64        `protobuf:"varint,5,opt,name=policy_valid_until_ms,json=policyValidUntilMs,proto3" json:"policy_valid_until_ms,omitempty"`
	Enabled            bool          `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Permissions        []*Permission `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Namespace          string        `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Opaque source metadata for reconciliation; not interpreted by this module.
	SourceContext []byte `protobuf:"bytes,9,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_authorization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{11}
}

func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Session) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Session) GetPasswordSha256() []byte {
	if x != nil {
		return x.PasswordSha256
	}
	return nil
}

func (x *Session) GetExpiresAtMs() uint64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *Session) GetPolicyValidUntilMs() uint64 {
	if x != nil {
		return x.PolicyValidUntilMs
	}
	return 0
}

func (x *Session) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Session) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Session) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Session) GetSourceContext() []byte {
	if x != nil {
		return x.SourceContext
	}
	return nil
}

type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy version captured before source reads. New identities and lease-only
	// renewals leave it stable; permission/source changes invalidate stale reads.
	ExpectedVersion string     `protobuf:"bytes,1,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Upserts         []*Session `protobuf:"bytes,2,rep,name=upserts,proto3" json:"upserts,omitempty"`
	Deletes         []string   `protobuf:"bytes,3,rep,name=deletes,proto3" json:"deletes,omitempty"`
	// Only inserts absent usernames. Existing sessions cannot be overwritten.
	// Does not require a version, and does not invalidate other sessions' grants.
	CreateOnly    bool `protobuf:"varint,4,opt,name=create_only,json=createOnly,proto3" json:"create_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_authorization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyRequest) GetExpectedVersion() string {
	if x != nil {
		return x.ExpectedVersion
	}
	return ""
}

func (x *ApplyRequest) GetUpserts() []*Session {
	if x != nil {
		return x.Upserts
	}
	return nil
}

func (x *ApplyRequest) GetDeletes() []string {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *ApplyRequest) GetCreateOnly() bool {
	if x != nil {
		return x.CreateOnly
	}
	return false
}

type ApplyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	PolicyRevision string                 `protobuf:"bytes,2,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_authorization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplyResponse) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	AfterUsername string                 `protobuf:"bytes,2,opt,name=after_username,json=afterUsername,proto3" json:"after_username,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_authorization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{14}
}

func (x *ListSessionsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListSessionsRequest) GetAfterUsername() string {
	if x != nil {
		return x.AfterUsername
	}
	return ""
}

func (x *ListSessionsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_authorization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{15}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListSessionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_authorization_proto protoreflect.FileDescriptor

const file_authorization_proto_rawDesc = "" +
	"\n" +
	"\x13authorization.proto\x12\x0emqtts.authz.v1\"\xd3\x01\n" +
	"\bDecision\x121\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x17.mqtts.authz.v1.OutcomeR\aoutcome\x12\"\n" +
	"\rexpires_at_ms\x18\x02 \x01(\x04R\vexpiresAtMs\x12 \n" +
	"\fcache_ttl_ms\x18\x03 \x01(\rR\n" +
	"cacheTtlMs\x12'\n" +
	"\x10cache_max_age_ms\x18\x04 \x01(\rR\rcacheMaxAgeMs\x12%\n" +
	"\x0ecache_revision\x18\x05 \x01(\tR\rcacheRevision\"j\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"\xeb\x01\n" +
	"\x10AuthorizeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12.\n" +
	"\x06action\x18\x04 \x01(\x0e2\x16.mqtts.authz.v1.ActionR\x06action\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1f\n" +
	"\vhas_payload\x18\a \x01(\bR\n" +
	"hasPayload\"U\n" +
	"\x15BatchAuthorizeRequest\x12<\n" +
	"\brequests\x18\x01 \x03(\v2 .mqtts.authz.v1.AuthorizeRequestR\brequests\"j\n" +
	"\x13AuthorizationResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x124\n" +
	"\bdecision\x18\x02 \x01(\v2\x18.mqtts.authz.v1.DecisionR\bdecision\"W\n" +
	"\x16BatchAuthorizeResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.mqtts.authz.v1.AuthorizationResultR\aresults\"8\n" +
	"\x0fRevisionRequest\x12%\n" +
	"\x0eknown_revision\x18\x01 \x01(\tR\rknownRevision\"~\n" +
	"\x10RevisionResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\tR\brevision\x123\n" +
	"\x15invalidated_usernames\x18\x02 \x03(\tR\x14invalidatedUsernames\x12\x19\n" +
	"\bis_delta\x18\x03 \x01(\bR\aisDelta\"\x8e\x01\n" +
	"\vJsonBinding\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12#\n" +
	"\requals_string\x18\x02 \x01(\tR\fequalsString\x12!\n" +
	"\fequals_topic\x18\x03 \x01(\bR\vequalsTopic\x12!\n" +
	"\frequired_any\x18\x04 \x01(\bR\vrequiredAny\"|\n" +
	"\rPayloadPolicy\x127\n" +
	"\bbindings\x18\x01 \x03(\v2\x1b.mqtts.authz.v1.JsonBindingR\bbindings\x122\n" +
	"\x15case_insensitive_keys\x18\x02 \x01(\bR\x13caseInsensitiveKeys\"\xa5\x01\n" +
	"\n" +
	"Permission\x12.\n" +
	"\x06action\x18\x01 \x01(\x0e2\x16.mqtts.authz.v1.ActionR\x06action\x12!\n" +
	"\ftopic_filter\x18\x02 \x01(\tR\vtopicFilter\x12D\n" +
	"\x0epayload_policy\x18\x03 \x01(\v2\x1d.mqtts.authz.v1.PayloadPolicyR\rpayloadPolicy\"\xdf\x02\n" +
	"\aSession\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12'\n" +
	"\x0fpassword_sha256\x18\x03 \x01(\fR\x0epasswordSha256\x12\"\n" +
	"\rexpires_at_ms\x18\x04 \x01(\x04R\vexpiresAtMs\x121\n" +
	"\x15policy_valid_until_ms\x18\x05 \x01(\x04R\x12policyValidUntilMs\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12<\n" +
	"\vpermissions\x18\a \x03(\v2\x1a.mqtts.authz.v1.PermissionR\vpermissions\x12\x1c\n" +
	"\tnamespace\x18\b \x01(\tR\tnamespace\x12%\n" +
	"\x0esource_context\x18\t \x01(\fR\rsourceContext\"\xa7\x01\n" +
	"\fApplyRequest\x12)\n" +
	"\x10expected_version\x18\x01 \x01(\tR\x0fexpectedVersion\x121\n" +
	"\aupserts\x18\x02 \x03(\v2\x17.mqtts.authz.v1.SessionR\aupserts\x12\x18\n" +
	"\adeletes\x18\x03 \x03(\tR\adeletes\x12\x1f\n" +
	"\vcreate_only\x18\x04 \x01(\bR\n" +
	"createOnly\"R\n" +
	"\rApplyResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12'\n" +
	"\x0fpolicy_revision\x18\x02 \x01(\tR\x0epolicyRevision\"w\n" +
	"\x13ListSessionsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12%\n" +
	"\x0eafter_username\x18\x02 \x01(\tR\rafterUsername\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x86\x01\n" +
	"\x14ListSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.mqtts.authz.v1.SessionR\bsessions\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor*H\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05ALLOW\x10\x01\x12\b\n" +
	"\x04DENY\x10\x02\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x03*<\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPUBLISH\x10\x01\x12\r\n" +
	"\tSUBSCRIBE\x10\x022\x91\x02\n" +
	"\rAuthorization\x12M\n" +
	"\fAuthenticate\x12#.mqtts.authz.v1.AuthenticateRequest\x1a\x18.mqtts.authz.v1.Decision\x12_\n" +
	"\x0eBatchAuthorize\x12%.mqtts.authz.v1.BatchAuthorizeRequest\x1a&.mqtts.authz.v1.BatchAuthorizeResponse\x12P\n" +
	"\vGetRevision\x12\x1f.mqtts.authz.v1.RevisionRequest\x1a .mqtts.authz.v1.RevisionResponse2\xb1\x01\n" +
	"\x0eAdministration\x12D\n" +
	"\x05Apply\x12\x1c.mqtts.authz.v1.ApplyRequest\x1a\x1d.mqtts.authz.v1.ApplyResponse\x12Y\n" +
	"\fListSessions\x12#.mqtts.authz.v1.ListSessionsRequest\x1a$.mqtts.authz.v1.ListSessionsResponseB5Z3github.com/ChangerR/mqtts/modules/authz/api/authzv1b\x06proto3"

var (
	file_authorization_proto_rawDescOnce sync.Once
	file_authorization_proto_rawDescData []byte
)

func file_authorization_proto_rawDescGZIP() []byte {
	file_authorization_proto_rawDescOnce.Do(func() {
		file_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)))
	})
	return file_authorization_proto_rawDescData
}

var file_authorization_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_authorization_proto_goTypes = []any{
	(Outcome)(0),                   // 0: mqtts.authz.v1.Outcome
	(Action)(0),                    // 1: mqtts.authz.v1.Action
	(*Decision)(nil),               // 2: mqtts.authz.v1.Decision
	(*AuthenticateRequest)(nil),    // 3: mqtts.authz.v1.AuthenticateRequest
	(*AuthorizeRequest)(nil),       // 4: mqtts.authz.v1.AuthorizeRequest
	(*BatchAuthorizeRequest)(nil),  // 5: mqtts.authz.v1.BatchAuthorizeRequest
	(*AuthorizationResult)(nil),    // 6: mqtts.authz.v1.AuthorizationResult
	(*BatchAuthorizeResponse)(nil), // 7: mqtts.authz.v1.BatchAuthorizeResponse
	(*RevisionRequest)(nil),        // 8: mqtts.authz.v1.RevisionRequest
	(*RevisionResponse)(nil),       // 9: mqtts.authz.v1.RevisionResponse
	(*JsonBinding)(nil),            // 10: mqtts.authz.v1.JsonBinding
	(*PayloadPolicy)(nil),          // 11: mqtts.authz.v1.PayloadPolicy
	(*Permission)(nil),             // 12: mqtts.authz.v1.Permission
	(*Session)(nil),                // 13: mqtts.authz.v1.Session
	(*ApplyRequest)(nil),           // 14: mqtts.authz.v1.ApplyRequest
	(*ApplyResponse)(nil),          // 15: mqtts.authz.v1.ApplyResponse
	(*ListSessionsRequest)(nil),    // 16: mqtts.authz.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 17: mqtts.authz.v1.ListSessionsResponse
}
var file_authorization_proto_depIdxs = []int32{
	0,  // 0: mqtts.authz.v1.Decision.outcome:type_name -> mqtts.authz.v1.Outcome
	1,  // 1: mqtts.authz.v1.AuthorizeRequest.action:type_name -> mqtts.authz.v1.Action
	4,  // 2: mqtts.authz.v1.BatchAuthorizeRequest.requests:type_name -> mqtts.authz.v1.AuthorizeRequest
	2,  // 3: mqtts.authz.v1.AuthorizationResult.decision:type_name -> mqtts.authz.v1.Decision
	6,  // 4: mqtts.authz.v1.BatchAuthorizeResponse.results:type_name -> mqtts.authz.v1.AuthorizationResult
	10, // 5: mqtts.authz.v1.PayloadPolicy.bindings:type_name -> mqtts.authz.v1.JsonBinding
	1,  // 6: mqtts.authz.v1.Permission.action:type_name -> mqtts.authz.v1.Action
	11, // 7: mqtts.authz.v1.Permission.payload_policy:type_name -> mqtts.authz.v1.PayloadPolicy
	12, // 8: mqtts.authz.v1.Session.permissions:type_name -> mqtts.authz.v1.Permission
	13, // 9: mqtts.authz.v1.ApplyRequest.upserts:type_name -> mqtts.authz.v1.Session
	13, // 10: mqtts.authz.v1.ListSessionsResponse.sessions:type_name -> mqtts.authz.v1.Session
	3,  // 11: mqtts.authz.v1.Authorization.Authenticate:input_type -> mqtts.authz.v1.AuthenticateRequest
	5,  // 12: mqtts.authz.v1.Authorization.BatchAuthorize:input_type -> mqtts.authz.v1.BatchAuthorizeRequest
	8,  // 13: mqtts.authz.v1.Authorization.GetRevision:input_type -> mqtts.authz.v1.RevisionRequest
	14, // 14: mqtts.authz.v1.Administration.Apply:input_type -> mqtts.authz.v1.ApplyRequest
	16, // 15: mqtts.authz.v1.Administration.ListSessions:input_type -> mqtts.authz.v1.ListSessionsRequest
	2,  // 16: mqtts.authz.v1.Authorization.Authenticate:output_type -> mqtts.authz.v1.Decision
	7,  // 17: mqtts.authz.v1.Authorization.BatchAuthorize:output_type -> mqtts.authz.v1.BatchAuthorizeResponse
	9,  // 18: mqtts.authz.v1.Authorization.GetRevision:output_type -> mqtts.authz.v1.RevisionResponse
	15, // 19: mqtts.authz.v1.Administration.Apply:output_type -> mqtts.authz.v1.ApplyResponse
	17, // 20: mqtts.authz.v1.Administration.ListSessions:output_type -> mqtts.authz.v1.ListSessionsResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_authorization_proto_init() }
func file_authorization_proto_init() {
	if File_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_authorization_proto_goTypes,
		DependencyIndexes: file_authorization_proto_depIdxs,
		EnumInfos:         file_authorization_proto_enumTypes,
		MessageInfos:      file_authorization_proto_msgTypes,
	}.Build()
	File_authorization_proto = out.File
	file_authorization_proto_goTypes = nil
	file_authorization_proto_depIdxs = nil
}
