'use strict';
const {Worker}=require('node:worker_threads');
const {createHash}=require('node:crypto');
const path=require('node:path');
const fs=require('node:fs');
const {authorizePath}=require('./tool-policy.cjs');
const MAX=8*1024*1024;
const mimeFor=name=>({'.txt':'text/plain','.md':'text/markdown','.csv':'text/csv','.pdf':'application/pdf','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})[path.extname(name).toLowerCase()];
function extractFile(bytes,mime,signal){signal?.throwIfAborted();return new Promise((resolve,reject)=>{const worker=new Worker(path.join(__dirname,'file-parser-worker.cjs'),{workerData:{bytes,mime},env:{},resourceLimits:{maxOldGenerationSizeMb:128,maxYoungGenerationSizeMb:32}});let settled=false;const done=(error,result)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);void worker.terminate();error?reject(error):resolve(result);};const abort=()=>done(signal.reason||new Error('File parsing cancelled'));const timer=setTimeout(()=>done(new Error('File parsing timeout')),15000);signal?.addEventListener('abort',abort,{once:true});worker.on('message',message=>done(message.error?new Error(message.error):null,message.result));worker.on('error',done);worker.on('exit',code=>{if(!settled)done(new Error(`File parser exited ${code}`));});});}
async function readAttachment(attachment,context){const id=attachment.asset?.id;if(!id||!context.getFile)throw new Error('File attachment requires an authorized stored asset');const asset=await context.getFile(id);if(asset.size>MAX)throw new Error('File exceeds 8 MiB limit');const url=asset.download_url||asset.url;if(!url)throw new Error('File has no authorized download URL');const response=await fetch(url,{signal:context.signal,redirect:'error'});if(!response.ok)throw new Error('File download failed');const reader=response.body.getReader();const chunks=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;if((size+=value.length)>MAX)throw new Error('File exceeds 8 MiB limit');chunks.push(Buffer.from(value));}}finally{await reader.cancel();}const bytes=Buffer.concat(chunks),hash=createHash('sha256').update(bytes).digest('hex');if(!asset.sha256||hash!==asset.sha256)throw new Error('File integrity verification failed');return {...await extractFile(bytes,asset.mime_type,context.signal),asset_id:id,sha256:hash,file_name:asset.file_name};}
function fileTools(roots,allowHidden,writeRoots=[]){const read={capabilities:['read'],idempotent:true};return [
{name:'local__file_extract',description:'Extract bounded text from TXT, Markdown, CSV, text PDF, DOCX or XLSX inside authorized roots. Scanned PDFs require OCR.',parameters:{type:'object',properties:{path:{type:'string'}},required:['path']},policy:read,invoke:async(args,signal)=>{const target=authorizePath(args.path,roots,allowHidden),stat=fs.statSync(target);if(!stat.isFile()||stat.size>MAX)throw new Error('File unavailable or oversized');return extractFile(fs.readFileSync(target),mimeFor(target),signal);}},
{name:'local__deliver_file',description:'Upload an existing real output file and return its persisted artifact record, version and authenticated download path.',parameters:{type:'object',properties:{path:{type:'string'}},required:['path']},policy:{capabilities:['read','deliver'],idempotent:true},invoke:async(args,signal,context)=>{signal.throwIfAborted();if(!context.deliverArtifact)throw new Error('Artifact delivery provider unavailable');const target=authorizePath(args.path,[...roots,...writeRoots],allowHidden),stat=fs.statSync(target);if(!stat.isFile()||stat.size>MAX)throw new Error('Output unavailable or oversized');const mime=mimeFor(target);if(!mime)throw new Error('Unsupported output format');return context.deliverArtifact({file_name:path.basename(target),mime_type:mime,content_base64:fs.readFileSync(target).toString('base64')});}}
,
{name:'local__create_table',description:'Write a real XLSX or CSV table into authorized output roots. Cell values are data; formulas are never evaluated.',parameters:{type:'object',properties:{path:{type:'string'},columns:{type:'array'},rows:{type:'array'}},required:['path','columns','rows']},policy:{capabilities:['write'],idempotent:true,approvalRequired:args=>fs.existsSync(args.path)},invoke:async(args,signal)=>{const target=authorizePath(args.path,writeRoots,allowHidden);if(args.columns.length>100||args.rows.length>10000||args.rows.some(row=>!Array.isArray(row)||row.length>100||row.some(value=>!['string','number','boolean'].includes(typeof value))))throw new Error('Invalid or oversized table');signal.throwIfAborted();let data;if(path.extname(target)==='.xlsx'){const book=new (require('exceljs').Workbook)();const sheet=book.addWorksheet('Result');sheet.addRows([args.columns,...args.rows]);data=Buffer.from(await book.xlsx.writeBuffer());}else if(path.extname(target)==='.csv'){data=Buffer.from([args.columns,...args.rows].map(row=>row.map(value=>'"'+String(value).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\n'));}else throw new Error('Table output must be CSV or XLSX');if(data.length>MAX)throw new Error('Output exceeds limit');signal.throwIfAborted();fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,data,{flag:fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_TRUNC|fs.constants.O_NOFOLLOW});return {path:target,bytes:data.length,rows:args.rows.length};}}
];}
module.exports={extractFile,readAttachment,fileTools,mimeFor};
