'use strict';
// Consume provider SSE frames, including UTF-8/codepoints and argument fragments
// split across network chunks. Never evaluate partial tool arguments.
async function consumeStream(response,{signal,onDelta}={}){
 const reader=response.body.getReader(),decoder=new TextDecoder();let pending='',content='',bytes=0,finished=false,doneFrame=false,lastEmit=0;const calls=new Map();
 async function frame(raw){const data=raw.split('\n').filter(line=>line.startsWith('data:')).map(line=>line.slice(5).trimStart()).join('\n');if(!data)return;if(data==='[DONE]'){doneFrame=true;return};const event=JSON.parse(data);if(event.error)throw new Error('Model stream failed: '+String(event.error.message||'provider error'));const choice=event.choices?.[0];if(!choice)return;const delta=choice.delta||{};if(typeof delta.content==='string')content+=delta.content;for(const fragment of delta.tool_calls||[]){if(!Number.isInteger(fragment.index)||fragment.index<0||fragment.index>64)throw new Error('Invalid streamed tool index');const call=calls.get(fragment.index)||{id:'',type:'function',function:{name:'',arguments:''}};call.id+=fragment.id||'';call.function.name+=fragment.function?.name||'';call.function.arguments+=fragment.function?.arguments||'';calls.set(fragment.index,call)}if(choice.finish_reason)finished=true;if(onDelta&&(Date.now()-lastEmit>=500||finished)){await onDelta(content);lastEmit=Date.now()}}
 try{while(true){signal?.throwIfAborted();const {done,value}=await reader.read();if(done)break;if((bytes+=value.length)>2*1024*1024)throw new Error('Model stream exceeds response limit');pending+=decoder.decode(value,{stream:true});pending=pending.replaceAll('\r\n','\n');let index;while((index=pending.indexOf('\n\n'))>=0){const raw=pending.slice(0,index);pending=pending.slice(index+2);await frame(raw)}}pending+=decoder.decode();if(pending.trim())await frame(pending);if(!finished||!doneFrame)throw new Error('Model stream ended before completion');await onDelta?.(content);return {choices:[{message:{role:'assistant',content,...(calls.size?{tool_calls:[...calls.entries()].sort((a,b)=>a[0]-b[0]).map(([,call])=>call)}:{})}}]};}finally{await reader.cancel()}
}
module.exports={consumeStream};
