'use client'
import {useEffect,useState} from 'react'
import {botsApi,memoryApi,schedulesApi,type AgentMemory,type AgentSchedule} from '@/lib/api'
import type {Bot} from '@/lib/types'
export function AssistantManagement(){
 const [bots,setBots]=useState<Bot[]>([]),[bot,setBot]=useState(''),[memories,setMemories]=useState<AgentMemory[]>([]),[schedules,setSchedules]=useState<AgentSchedule[]>([]),[content,setContent]=useState(''),[editing,setEditing]=useState<string>(),[title,setTitle]=useState(''),[prompt,setPrompt]=useState(''),[when,setWhen]=useState(''),[timezone,setTimezone]=useState('Asia/Shanghai'),[recurrence,setRecurrence]=useState('once'),[missed,setMissed]=useState('once'),[error,setError]=useState('')
 const reload=async()=>{const [b,m,s]=await Promise.all([botsApi.list(),memoryApi.list(),schedulesApi.list()]);setBots(b);setMemories(m);setSchedules(s);setBot(value=>value||b[0]?.id||'')}
 useEffect(()=>{void reload().catch(e=>setError(e.message))},[])
 const perform=async(action:()=>Promise<unknown>)=>{try{await action();await reload();setError('')}catch(e){setError(e instanceof Error?e.message:'操作失败')}}
 const exportMemory=async()=>{const rows=await memoryApi.export();const url=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='confirmed-memories.json';a.click();URL.revokeObjectURL(url)}
 return <section className="space-y-4" aria-label="记忆与计划"><label>助手<select className="border ml-2" value={bot} onChange={e=>setBot(e.target.value)}>{bots.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>{error&&<p role="alert">{error}</p>}
 <h2 className="text-xl">已确认记忆</h2><p>保存到当前助手的个人作用域。删除后会清除派生上下文，下一次工作重新检索。</p><textarea className="border w-full" aria-label="记忆内容" value={content} onChange={e=>setContent(e.target.value)}/><button onClick={()=>void perform(async()=>{await memoryApi.save({bot_id:bot,scope:'personal',content,source:'user_confirmation',confirmed:true},editing);setContent('');setEditing(undefined)})}>确认保存记忆</button><button className="ml-4" onClick={()=>void perform(exportMemory)}>导出记忆</button>{memories.map(m=><article className="border p-3" key={m.id}><p>{m.content}</p><small>{m.scope} · 来源 {m.source}</small><div><button onClick={()=>{setBot(m.bot_id);setContent(m.content);setEditing(m.id)}}>修改</button><button className="ml-4" onClick={()=>void perform(()=>memoryApi.remove(m.id))}>删除</button></div></article>)}
 <h2 className="text-xl">计划任务</h2><form className="space-y-2" onSubmit={e=>{e.preventDefault();void perform(async()=>{await schedulesApi.create({bot_id:bot,title,prompt,local_time:when,timezone,recurrence,missed_policy:missed});setTitle('');setPrompt('')})}}><label>标题<input required className="border ml-2" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block">工作内容<textarea required className="border w-full" value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><label>当地时间<input required type="datetime-local" className="border ml-2" value={when} onChange={e=>setWhen(e.target.value)}/></label><label className="block">时区<input className="border ml-2" value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><label>重复<select className="border ml-2" value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="once">一次</option><option value="daily">每天</option><option value="weekly">每周</option></select></label><label className="block">错过时间<select className="border ml-2" value={missed} onChange={e=>setMissed(e.target.value)}><option value="once">补跑一次</option><option value="skip">跳过</option></select></label><button type="submit">创建计划</button></form>
 {schedules.map(s=><article className="border p-3" key={s.id}><h3>{s.title}</h3><p>{s.status} · {s.recurrence} · {s.timezone} · 下次 {s.next_at}</p>{s.last_task_status === "failed"&&<p role="alert">最近执行失败：{s.last_task_note||"请查看任务步骤并恢复"}</p>}{s.last_task_id&&<a href="/tasks">查看最近任务及结果</a>}{['active','paused'].includes(s.status)&&<div><button onClick={()=>void perform(()=>schedulesApi.action(s.id,s.status==='active'?'pause':'resume'))}>{s.status==='active'?'暂停':'恢复'}</button><button className="ml-4" onClick={()=>void perform(()=>schedulesApi.action(s.id,'cancel'))}>取消计划</button></div>}</article>)}</section>
}
