package service

import (
	"context"
	"errors"
	"testing"

	"github.com/google/uuid"
	"github.com/openclaw-bot-chat/backend/internal/model"
	"github.com/openclaw-bot-chat/backend/internal/repository"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func TestDocumentCreateListUpdateArchive(t *testing.T) {
	env := newDocumentServiceTestEnv(t)
	ctx := context.Background()

	document, err := env.service.Create(ctx, env.ownerID, CreateDocumentRequest{
		Title: "AI 编程学习路线",
		Body:  "# AI 编程学习路线\n\n第一周：工具链。",
	})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if document.ID == uuid.Nil {
		t.Fatal("Create() did not assign document id")
	}
	if document.Source != model.DocumentSourceUser {
		t.Fatalf("Create() source = %q, want user", document.Source)
	}
	if document.Summary == "" {
		t.Fatal("Create() did not derive summary")
	}

	list, err := env.service.List(ctx, env.ownerID, 20)
	if err != nil {
		t.Fatalf("List() error = %v", err)
	}
	if len(list) != 1 || list[0].ID != document.ID {
		t.Fatalf("List() = %#v, want created document", list)
	}

	updatedTitle := "AI Agent 学习路线"
	updatedBody := "# AI Agent 学习路线\n\n加入部署章节。"
	updated, err := env.service.Update(ctx, env.ownerID, document.ID, UpdateDocumentRequest{
		Title: &updatedTitle,
		Body:  &updatedBody,
	})
	if err != nil {
		t.Fatalf("Update() error = %v", err)
	}
	if updated.Title != updatedTitle || updated.Body != updatedBody {
		t.Fatalf("Update() = title:%q body:%q", updated.Title, updated.Body)
	}

	reloaded, err := env.service.Get(ctx, env.ownerID, document.ID)
	if err != nil {
		t.Fatalf("Get() error = %v", err)
	}
	if reloaded.Body != updatedBody {
		t.Fatalf("Get() body = %q, want persisted update", reloaded.Body)
	}

	if err := env.service.Archive(ctx, env.ownerID, document.ID); err != nil {
		t.Fatalf("Archive() error = %v", err)
	}
	list, err = env.service.List(ctx, env.ownerID, 20)
	if err != nil {
		t.Fatalf("List() after archive error = %v", err)
	}
	if len(list) != 0 {
		t.Fatalf("List() after archive = %#v, want empty", list)
	}
	if _, err := env.service.Get(ctx, env.ownerID, document.ID); !errors.Is(err, ErrDocumentNotFound) {
		t.Fatalf("Get() after archive error = %v, want ErrDocumentNotFound", err)
	}
}

func TestDocumentOwnerIsolation(t *testing.T) {
	env := newDocumentServiceTestEnv(t)
	ctx := context.Background()
	otherUserID := uuid.New()

	document, err := env.service.Create(ctx, env.ownerID, CreateDocumentRequest{
		Title: "Private",
		Body:  "Owner only",
	})
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if _, err := env.service.Get(ctx, otherUserID, document.ID); !errors.Is(err, ErrDocumentNotFound) {
		t.Fatalf("Get() as other user error = %v, want ErrDocumentNotFound", err)
	}
	otherList, err := env.service.List(ctx, otherUserID, 20)
	if err != nil {
		t.Fatalf("List() as other user error = %v", err)
	}
	if len(otherList) != 0 {
		t.Fatalf("List() as other user = %#v, want empty", otherList)
	}
}

func TestCreateBotDocumentSetsSourceAndMessageMetadata(t *testing.T) {
	env := newDocumentServiceTestEnv(t)
	ctx := context.Background()
	botID := uuid.New()

	document, err := env.service.CreateFromBot(ctx, env.ownerID, botID, CreateDocumentRequest{
		Title: "Bot Draft",
		Body:  "Generated by bot.",
	})
	if err != nil {
		t.Fatalf("CreateFromBot() error = %v", err)
	}
	if document.Source != model.DocumentSourceBot {
		t.Fatalf("CreateFromBot() source = %q, want bot", document.Source)
	}
	if document.SourceBotID == nil || *document.SourceBotID != botID {
		t.Fatalf("CreateFromBot() bot id = %v, want %s", document.SourceBotID, botID)
	}
}

type documentServiceTestEnv struct {
	service *DocumentService
	ownerID uuid.UUID
}

func newDocumentServiceTestEnv(t *testing.T) documentServiceTestEnv {
	t.Helper()
	db, err := gorm.Open(sqlite.Open("file:"+uuid.NewString()+"?mode=memory&cache=shared"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	if err := db.Exec(`
		CREATE TABLE documents (
			id text PRIMARY KEY,
			owner_id text NOT NULL,
			title text NOT NULL,
			summary text,
			body text,
			document_type text NOT NULL DEFAULT 'markdown',
			source text NOT NULL DEFAULT 'user',
			status text NOT NULL DEFAULT 'active',
			source_bot_id text,
			source_conversation_id text,
			source_message_id text,
			metadata text,
			created_at datetime,
			updated_at datetime,
			deleted_at datetime
		)
	`).Error; err != nil {
		t.Fatalf("migrate documents: %v", err)
	}
	return documentServiceTestEnv{
		service: NewDocumentService(repository.NewDocumentRepository(db)),
		ownerID: uuid.New(),
	}
}
