#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
export OPENCLAW_ENV_FILE="${OPENCLAW_ENV_FILE:-$SCRIPT_DIR/dev.env}"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/common.sh"

create_env_file() {
  local jwt_secret
  local mqtt_password
  local database_password

  jwt_secret="$(generate_secret)"
  mqtt_password="$(generate_secret)"
  database_password="$(generate_secret)"

  cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/dev-up.sh
# Public domain used during development. Adjust if you are not using the
# bundled Nginx config on test.iotdevices.site.
DOMAIN=test.iotdevices.site
PUBLIC_SCHEME=https

# Docker project
COMPOSE_PROJECT_NAME=openclaw-bot-chat-dev

# Reverse proxy / published ports
FRONTEND_PORT_MAPPING=127.0.0.1:4173:3000
BACKEND_PORT_MAPPING=127.0.0.1:18080:8080
REDIS_PORT_MAPPING=127.0.0.1:6379:6379
MQTT_TCP_PORT_MAPPING=127.0.0.1:1883:1883
MQTT_WS_PORT_MAPPING=127.0.0.1:8083:8083
EMQX_DASHBOARD_PORT_MAPPING=127.0.0.1:18083:18083

# Frontend dev server runtime
NEXT_PUBLIC_API_URL=https://test.iotdevices.site
MQTT_TCP_PUBLIC_URL=mqtt://127.0.0.1:1883
MQTT_WS_PUBLIC_URL=wss://test.iotdevices.site/mqtt

# Fixed development test account
DEV_TEST_USERNAME=tester
DEV_TEST_EMAIL=tester@example.com
DEV_TEST_PASSWORD=test123456
DEV_TEST_NICKNAME="Test User"

# Backend runtime
APP_MODE=release
LOG_LEVEL=debug
DATABASE_USER=postgres
DATABASE_PASSWORD=$database_password
DATABASE_DBNAME=openclaw_bot_chat
MQTT_USERNAME=openclaw_backend
MQTT_PASSWORD=$mqtt_password
JWT_SECRET=$jwt_secret
EOF

  echo "Created $ENV_FILE"
}

load_dev_env() {
  load_env_file

  : "${DEV_TEST_USERNAME:=tester}"
  : "${DEV_TEST_EMAIL:=tester@example.com}"
  : "${DEV_TEST_PASSWORD:=test123456}"
  : "${DEV_TEST_NICKNAME:=Test User}"

  export DEV_TEST_USERNAME
  export DEV_TEST_EMAIL
  export DEV_TEST_PASSWORD
  export DEV_TEST_NICKNAME
}

frontend_dependencies_stale() {
  local frontend_dir

  frontend_dir="$REPO_ROOT/frontend"

  if [[ ! -d "$frontend_dir/node_modules" ]]; then
    return 0
  fi

  if [[ ! -f "$frontend_dir/node_modules/.package-lock.json" ]]; then
    return 0
  fi

  if [[ "$frontend_dir/package-lock.json" -nt "$frontend_dir/node_modules/.package-lock.json" ]]; then
    return 0
  fi

  if [[ "$frontend_dir/package.json" -nt "$frontend_dir/node_modules/.package-lock.json" ]]; then
    return 0
  fi

  return 1
}

ensure_frontend_dependencies() {
  if ! frontend_dependencies_stale; then
    return 0
  fi

  (
    cd "$REPO_ROOT/frontend"
    npm ci
  )
}

frontend_dev_listening() {
  parse_frontend_mapping
  ss -ltn "( sport = :${FRONTEND_BIND_PORT} )" 2>/dev/null | awk 'NR > 1 { found = 1 } END { exit found ? 0 : 1 }'
}

print_frontend_dev_status() {
  parse_frontend_mapping

  if frontend_dev_listening; then
    echo "Frontend dev server: listening on ${FRONTEND_BIND_HOST}:${FRONTEND_BIND_PORT}"
    return 0
  fi

  echo "Frontend dev server: not running (start ./scripts/dev-front.sh in another terminal)"
  return 1
}

sql_escape_literal() {
  printf "%s" "$1" | sed "s/'/''/g"
}

wait_for_dev_postgres() {
  local i

  for i in $(seq 1 30); do
    if compose exec -T postgres pg_isready -U "${DATABASE_USER:-postgres}" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done

  echo "Postgres did not become ready in time." >&2
  return 1
}

ensure_dev_test_account() {
  local username_sql
  local email_sql
  local password_sql
  local nickname_sql

  wait_for_dev_postgres

  username_sql="$(sql_escape_literal "$DEV_TEST_USERNAME")"
  email_sql="$(sql_escape_literal "$DEV_TEST_EMAIL")"
  password_sql="$(sql_escape_literal "$DEV_TEST_PASSWORD")"
  nickname_sql="$(sql_escape_literal "$DEV_TEST_NICKNAME")"

  compose exec -T postgres psql \
    -U "$DATABASE_USER" \
    -d "$DATABASE_DBNAME" \
    -v ON_ERROR_STOP=1 <<SQL
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO \$\$
DECLARE
    existing_id UUID;
BEGIN
    SELECT id INTO existing_id
    FROM users
    WHERE username = '${username_sql}' OR email = '${email_sql}'
    ORDER BY CASE
        WHEN username = '${username_sql}' AND email = '${email_sql}' THEN 0
        WHEN email = '${email_sql}' THEN 1
        ELSE 2
    END
    LIMIT 1;

    IF existing_id IS NOT NULL THEN
        DELETE FROM users
        WHERE id <> existing_id
          AND (username = '${username_sql}' OR email = '${email_sql}');

        UPDATE users
        SET username = '${username_sql}',
            email = '${email_sql}',
            password_hash = crypt('${password_sql}', gen_salt('bf', 12)),
            nickname = '${nickname_sql}',
            status = 1,
            is_deleted = false,
            updated_at = NOW()
        WHERE id = existing_id;
    ELSE
        INSERT INTO users (
            username,
            email,
            password_hash,
            nickname,
            status,
            is_deleted
        ) VALUES (
            '${username_sql}',
            '${email_sql}',
            crypt('${password_sql}', gen_salt('bf', 12)),
            '${nickname_sql}',
            1,
            false
        );
    END IF;
END
\$\$;
SQL
}

print_dev_test_credentials() {
  cat <<EOF
Dev test account:
  username: ${DEV_TEST_USERNAME}
  email:    ${DEV_TEST_EMAIL}
  password: ${DEV_TEST_PASSWORD}
EOF
}

print_dev_runtime_summary() {
  parse_frontend_mapping
  parse_backend_mapping

  cat <<EOF
Domain:              ${DOMAIN}
Frontend dev URL:    http://${DOMAIN}
Frontend dev bind:   ${FRONTEND_BIND_HOST}:${FRONTEND_BIND_PORT}
Backend upstream:    ${BACKEND_BIND_HOST}:${BACKEND_BIND_PORT}
API base:            ${NEXT_PUBLIC_API_URL}
Broker WS URL:       ${MQTT_WS_PUBLIC_URL}
Env file:            ${ENV_FILE}
EOF
}
